### ISSUE TITLE
investigate production deployment

### ISSUE THREAD

**Issue by balmas** [Capitains/Nautilus#14]
we need to investigate and document production deployment options

this link from @PonteIneptique might be helpful

http://blog.kgriffs.com/2012/12/18/uwsgi-vs-gunicorn-vs-node-benchmarks.html

**Comment by balmas** [comment]
http://developers-club.com/posts/267097/

**Comment by PonteIneptique** [comment]
Probably the best article and most recent : http://www.philchen.com/2015/08/08/how-to-make-a-scalable-python-web-app-using-flask-and-gunicorn-nginx-on-ubuntu-14-04

**Comment by PonteIneptique** [comment]
I think we can say it's done :)
