### ISSUE TITLE
Add a command (in command line) for pre-computing and pre-caching the inventory

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Nautilus#15]
On low memory devices, this is actually impossible to do otherwise without increasing timeout limits.

`capitains-nautilus-cache` should be a new command

- `capitains-nautilus-cache empty cache-prefix` - Clean cache
- `capitains-nautilus-cache pre-cache path/to/app.py blueprint_variable_name` - Open the blueprint in the python file and compute the cache for inventories.

@balmas What do you think ?

**Comment by balmas** [comment]
it sounds like a useful thing to me.
