### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by balmas** [Capitains/Nautilus#2]
I propose Nautilus should implement the CTS 5 "inventory" as follows:
1. Inventory Definition Objects can be supplied in the server configuration to define named subsets of texts
   1. the objects contain simple lists of URNs
   2. the granularity of the URN defines the scope of textual data included for that URN, i.e:
      1. supplying a textgroup urn means include all available data for this textgroup and its children
      2. supplying a work urn means include all available data for this work and its children
      3. supplying a version urn means include all available data for this version
      4. an optional nice-to-have feature would be to have a syntax which allows for exclusion of texts by work or version URN (i.e. so that you can include all items from a textgroup **except** this work, version etc.)
2. Nautilus always constructs the TextInventory response to a GetCapabilities request dynamically based upon the data in the Inventory Definition Object, pulling the appropriate data from the `__cts__.xml` files and the refsDecl of the tei files.
3. Only GetCapabilities supports the inventory parameter.  Because inventories always describe subsets of the larger repository, when retrieving data from a file specific file in the repo (as in the GetValidReff and GetPassagePlus requests) the inventory parameter is extraneous and if supplied is ignored.
4. If inventory parameter is not supplied to GetCapabilities, the entire contents of the repo are used to construct the TextInventory response. In this way the inventory operates as a **filter** on the functionality, rather than as a **driver**.

@PonteIneptique what do you think? What am I overlooking?

**Comment by PonteIneptique** [comment]
1. I'll try to propose skeletons for the 1. Probably something like `{'mode': 'exclusive/inclusive[default]', 'resources': ['urn:cts:latinLit:phi1294', ...]}`
2. It is already the case, which is good. The only thing which needs to be added is cache.
3. Agree
4. Agree

I do not think you overlooked anything. Will see in the next days if that's the case.

**Comment by PonteIneptique** [comment]
Somehow fixed by Dispatcher at the moment - https://github.com/Capitains/Nautilus/commit/c3dce9b8d46acee6cf81162c485b5ef7c736193d

**Comment by PonteIneptique** [comment]
I think the dispatcher somehow fixed this question. This is too much a legacy question given the current goals of Capitains to decouple from CTS
