### ISSUE TITLE
Improve performance from IO to down to the XPATH retrieval

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Nautilus#31]
The question of how we access our XML files/LXML Files is quite important right now. We do access direct files with read only mode. We should see what kind of performance we could gain here.

@mittagessen @fbaumgardt and @sonofmun I would be really happy to have your feedback on this. This is a question that needs to be resolved, even if the answer is : we are doing the best available. We cannot accept to have to run on huge RAM capable server when it comes to simple webservers.

**Comment by PonteIneptique** [comment]
We are continuously reading the file and reparsing them right now, here is where it happens : https://github.com/Capitains/Nautilus/blob/master/capitains_nautilus/inventory/local.py#L20

**Comment by PonteIneptique** [comment]
Another element for the discussion : https://charlesleifer.com/blog/completely-un-scientific-benchmarks-of-some-embedded-databases-with-python/ . I would need to add some Disk IO comparison though.

**Comment by PonteIneptique** [comment]
One of my feeling is that indexing (XPATH results) would be a good thing but I could be wrong.

**Comment by fbaumgardt** [comment]
1) I'd index and keep checksums for the files to efficiently spot file changes and re-index those. In case you’re not doing that already.

2) Consider moving indexes like the inventory into a K-V store, that is probably more efficient than doing it natively in Python.

3) Also, it looks to me as if you’re parsing full XML trees. Using SAX or Stax would be more efficient.

Hope any of this makes sense — I only had time to skim the code and might be way off.

**Comment by PonteIneptique** [comment]
I'll try to reply to this first comment : 
1) I totally agree, this is the first step to take. This will save IO for sure. Maybe not checksum for the moment (we could reparse everything when needed for now)
2) I think I agree, if this is what I think it is. Would need to be benchmarked though.
3) Yes I am. This is an important question I have to benchmark. I'll probably try to benchmark this quickly. The issue is also the availability of strong parsers to some extent but in the context of our system, maybe streamed would be more efficient (not TOTALLY sure but could be)

**Comment by fbaumgardt** [comment]
Agree on 2). I don’t have practical experience with it and can easily imagine that there’s a break-even point where communication overhead is eating up theoretical speed gains. I.e. if the index is too small, it’ll be slower to do externally. On the other hand a KV-store's built-in persistence makes 1) easy.

3) For scenarios where you don’t have to do many rapidly repeating accesses (i.e. >100s) to addresses inside the document SAX is definitely preferable. I usually model a simple XPATH on the side, but for your purposes looking for a StAX parser is a better choice. libxml2 has one and there are Python bindings for it.

**Comment by PonteIneptique** [comment]
Fixed by https://github.com/Capitains/Nautilus/commit/c3dce9b8d46acee6cf81162c485b5ef7c736193d
