### ISSUE TITLE
flush doesn't completely clear the cache

### ISSUE THREAD

**Issue by balmas** [Capitains/Nautilus#34]
Ran into an interesting problem today.  A new version of a text was deployed which added previously missing passages at citation level 2.  The GetValidReff command for level 2 was cached and the flush command did not clear it. I had to do a hard flush of the redis cache to resolve this.

i.e. this request:

`http://cts.perseids.org/api/cts/?request=GetValidReff&urn=urn:cts:pdlpsci:bodin.livrep.perseus-fre1&level=2`

remained cached

But this one (apparently) did not:

`http://cts.perseids.org/api/cts/?request=GetValidReff&urn=urn:cts:pdlpsci:bodin.livrep.perseus-fre1:1`

**Comment by PonteIneptique** [comment]
I am not sure to know where it comes from frankly. Have tried to find a reason for it but normaly caching should remove everything atm...

**Comment by PonteIneptique** [comment]
I am not sure to know where it comes from frankly. Have tried to find a reason for it but normaly caching should remove everything atm...
