### ISSUE TITLE
After death of first worker, loss of metadata

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Nautilus#44]
https://github.com/Capitains/flask-capitains-nemo/issues/104

## Reproduction steps
Here is the reproduction steps ( that would need to be made possible to recreate in Travis when we have a fix ):

1. Clear the cache
2. Create a resolver with a Cache object
3. Parse with `resolver.parse()`
4. Leave the current python session (== death of worker)
5. Go to retriever
6. Require any other resource than `resolver.inventory` or its TextInventories (direct members of TextInventoryCollection)
7. Metadata are empty.

## Idea for unit test

- `subprocess` for travis / local tests in setUp

**Comment by PonteIneptique** [comment]
Try to check if the issue is related to the grapg caching

**Comment by PonteIneptique** [comment]
Given the fact that an item showing None on Nemo display has the following answer lacking metadata, it most certainly is the Graph.
Need to figure if we cache it or store it.

http://ctsstage.dh.uni-leipzig.de/api/cts?request=GetCapabilities&urn=urn:cts:latinLit:phi0845

```xml
<GetCapabilities><request><requestName>GetInventory</requestName><requestFilters>urn=urn:cts:latinLit:phi0845</requestFilters></request><reply><TextInventory tiid="urn:perseus:latinLit"><textgroup urn="urn:cts:latinLit:phi0845"><work xml:lang="None" urn="urn:cts:latinLit:phi0845.phi002" groupUrn="urn:cts:latinLit:phi0845"><edition xml:lang="None" workUrn="urn:cts:latinLit:phi0845.phi002" urn="urn:cts:latinLit:phi0845.phi002.perseus-lat3"><online><citationMapping><citation label="book" xpath="/tei:div[@n='?']" scope="/tei:TEI/tei:text/tei:body/tei:div"><citation label="chapter" xpath="/tei:div[@n='?']" scope="/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='?']"><citation label="section" xpath="/tei:div[@n='?']" scope="/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='?']/tei:div[@n='?']"/></citation></citation></citationMapping></online></edition></work></textgroup></TextInventory></reply></GetCapabilities>
```

**Comment by PonteIneptique** [comment]
```python
>>> from app import resolver
INFO:rdflib:RDFLib Version: 4.2.2
>>> resolver.inventory
TextInventoryCollection(default)
>>> resolver.inventory["urn:cts:latinLit:phi0845"]
TextGroup(urn:cts:latinLit:phi0845)
>>> resolver.inventory["urn:cts:latinLit:phi0845"].metadata
<MyCapytain.common.metadata.Metadata object at 0x7ff2f5039080>
>>> resolver.inventory["urn:cts:latinLit:phi0845"].metadata.export9)
  File "<stdin>", line 1
    resolver.inventory["urn:cts:latinLit:phi0845"].metadata.export9)
                                                                   ^
SyntaxError: invalid syntax
>>> resolver.inventory["urn:cts:latinLit:phi0845"].metadata.export()
{'http://www.w3.org/2004/02/skos/core#prefLabel': {'eng': 'Columella, Lucius Junius Moderatus.'}, 'http://chs.harvard.edu/xmlns/cts/groupname': {'eng': 'Columella, Lucius Junius Moderatus.'}}
>>> resolver.getMetadata("urn:cts:latinLit:phi0845").metadata.export()
{}
>>> resolver.getMetadata("urn:cts:latinLit:phi0845")
TextGroup(urn:cts:latinLit:phi0845)
>>> resolver.getMetadata("urn:cts:latinLit:phi0845").metadata
<MyCapytain.common.metadata.Metadata object at 0x7ff2f5113a58>
>>> resolver.getMetadata("urn:cts:latinLit:phi0845").metadata
```

**Comment by PonteIneptique** [comment]
Reproducing the bug is extremely uneasy...

**Comment by PonteIneptique** [comment]
Metadata nodes are different :

**Comment by PonteIneptique** [comment]
Not an issue with metadata.getOr but rather with graph !
```python
>>> resolver.inventory["urn:cts:latinLit:phi0845"].graph
<Graph identifier=Nc1c8bfb63e0645f1bf790944e74ab3d1 (<class 'rdflib.graph.Graph'>)>
>>> resolver.getMetadata("urn:cts:latinLit:phi0845").graph
<Graph identifier=N2c5ad24d625848d694e6f34407e111b3 (<class 'rdflib.graph.Graph'>)>
>>> resolver.getMetadata("urn:cts:latinLit:phi1294").graph
<Graph identifier=N2c5ad24d625848d694e6f34407e111b3 (<class 'rdflib.graph.Graph'>)>
>>> resolver.inventory["urn:cts:latinLit:phi1294"].graph
<Graph identifier=Nc1c8bfb63e0645f1bf790944e74ab3d1 (<class 'rdflib.graph.Graph'>)>
```

Two different graphs

**Comment by PonteIneptique** [comment]
So, here is the reproduction steps ( that would need to be made possible to recreate in Travis when we have a fix ):

1. Clear the cache
2. Create a resolver with a Cache object
3. Parse with `resolver.parse()`
4. Leave the current python session (== death of worker)
5. Go to retriever
6. Require any other resource than `resolver.inventory` or its TextInventories (direct members of TextInventoryCollection)
7. Metadata are empty.

**Comment by PonteIneptique** [comment]
Current hacky fix : 

```python
    def getMetadata(self, objectId=None, **filters):
        """ Request metadata about a text or a collection

        :param objectId: Object Identifier to filter on
        :type objectId: str
        :param filters: Kwargs parameters.
        :type filters: dict
        :return: Collection
        """
        #global MyCapytain.common.constants.GRAPH = self.inventory.graph
        #global GRAPH
        """
        print(self.inventory.graph.identifier, constants.GRAPH.identifier, GRAPH.identifier)
        constants.GRAPH = self.inventory.graph
        print(self.inventory.graph.identifier, constants.GRAPH.identifier, GRAPH.identifier)
        x = self.get_or(
            _cache_key("Nautilus", self.name, "GetMetadata", objectId),
            CTSCapitainsLocalResolver.getMetadata, self, objectId
        )
        x.__graph__ = self.inventory.graph
        x.metadata.__graph__ = x.__graph__
        return x
        """
        if objectId is None:
            return self.inventory
        elif objectId in self.inventory.children.keys():
            return self.inventory[objectId]
        texts, _, _ = self.__getTextMetadata__(urn=objectId)

        # We store inventory names and if there is only one we recreate the inventory
        inv_names = [text.parent.parent.parent.id for text in texts]
        if len(set(inv_names)) == 1:
            inventory = TextInventory(name=inv_names[0])
        else:
            inventory = TextInventory()
        # For each text we found using the filter
        for text in texts:
            tg_urn = str(text.parent.parent.urn)
            wk_urn = str(text.parent.urn)
            txt_urn = str(text.urn)
            # If we need to generate a textgroup object
            if tg_urn not in inventory.textgroups:
                tg = TextGroup(urn=tg_urn, parent=inventory)
                tg.__metadata__ = self.inventory[tg_urn].metadata
                tg.__graph__ = self.inventory.graph
            # If we need to generate a work object
            if wk_urn not in inventory.textgroups[tg_urn].works:
                w = Work(urn=wk_urn, parent=inventory.textgroups[tg_urn])
                w.__metadata__ = self.inventory[wk_urn].metadata
                w.__graph__ = self.inventory.graph
            if isinstance(text, Edition):
                x = Edition(urn=txt_urn, parent=inventory.textgroups[tg_urn].works[wk_urn])
                x.citation = text.citation
                x.__metadata__ = self.inventory[txt_urn].metadata
                x.__graph__ = self.inventory.graph

            elif isinstance(text, Translation):
                x = Translation(urn=txt_urn, parent=inventory.textgroups[tg_urn].works[wk_urn])
                x.__metadata__ = self.inventory[txt_urn].metadata
                x.citation = text.citation
                x.__graph__ = self.inventory.graph
                # Need to set lang as well...


        return inventory[objectId]

**Comment by PonteIneptique** [comment]
@fbaumgardt if you have some thoughts about this issue (which I hope I described well), they are welcome.
The major issue is that Translation, Edition, etc.. are referring to another constants.GRAPH instance than the inventory (which we got back from cache).

**Comment by PonteIneptique** [comment]
@fbaumgardt @balmas if you want to have an idea of what's happening, I was just able to set up a test class to reproduce the bug https://github.com/Capitains/Nautilus/commit/19291fa72c2fa96614c56d0137abd4c0ce6ff254

**Comment by fbaumgardt** [comment]
Thanks, I don't yet fully understand the issue, working on it.

**Comment by PonteIneptique** [comment]
@fbaumgardt Trying to reformulate the issue : 

1. Before caching, MyCapytain spawns an RDFLib graph with an IOStore (Graph1)
2. At caching, the graph is cached with the inventory in the resolver (using Mycapytain graph (inventory.graph))
3. Process dies, IOStore is deleted
4. We enter a second process
5. MyCapytain spawns a new RDFLib Graph  with an IOStore (Graph2)
6. The whole MyCapytain modules refers to Graph 2
7. We load the inventory from cache. cache.inventory is still Graph 1.
8. When we try to get metadata from the graph (See Metadata.getOr in MyCapytain or CTSLocalResolver.getMetadata), it refers to Graph 2 because Metadata and Collection class (not instances) are refering to Graph 2.
9. The way to hack our way right now is to replace each object graph instance with the cached object.

The best way would be to be able to overwrite the constant Graph2 of MyCapytain with the inventory.graph loaded from cache (Graph 1). Up to now, I was not able to perform such a hack.

**Comment by PonteIneptique** [comment]
Feel free to ask question if something is not clear.

**Comment by PonteIneptique** [comment]
(Objective is to be able to keep the Graph with an IOStore)

**Comment by PonteIneptique** [comment]
I might have found a fix...

**Comment by PonteIneptique** [comment]
Give me your feeling on this : 

- Replace each GRAPH direct call in MyCapytain with get_graph()
- Replace Graph instantiation in MyCapytain.common.constants with

```python
global GRAPH
GRAPH = Graph()
GRAPH.bind("", NAMESPACES.CTS)
GRAPH.bind("dts", NAMESPACES.DTS)
GRAPH.bind("tei", NAMESPACES.TEI)
GRAPH.bind("skos", SKOS)


def set_graph(graph):
    global GRAPH
    GRAPH = graph


def get_graph():
    return GRAPH
``
- Replace inventory getter in Nautilus.cts.resolver with 

```python
    @property
    def inventory(self):
        if self.__inventory__ is None or len(self.__inventory__.readableDescendants) == 0:
            self.__inventory__ = self.get_or(self.inventory_cache_key, self.parse, self.__resources__)
            set_graph(self.__inventory__.graph)
        return self.__inventory__
```

**Comment by fbaumgardt** [comment]
Great! I still lack a lot of the necessary understandiung of the whole, my current impression is that in

https://github.com/Capitains/MyCapytain/blob/master/MyCapytain/resolvers/cts/local.py#L307

and subsequently

https://github.com/Capitains/MyCapytain/blob/0bb48d1ebfc70a6517a4495122616b11030ca1b1/MyCapytain/resources/prototypes/cts/inventory.py#L39

you create the resource anytime it gets requested with a new Graph instance and never check the cache for existing copies?

**Comment by fbaumgardt** [comment]
W.r.t. https://github.com/Capitains/Nautilus/issues/44#issuecomment-283096565: Again, I don't have a clear picture of the architecture, but would be hesitant to add globals if it's possible to limit scope. (Not saying it is possible, but suggesting you think about it.)

**Comment by PonteIneptique** [comment]
I was using global Graph yes but the way it was set up were "damaging" by making it possible to have concurrent graph everywhere. Now it's fixed.

Although, I made the graph name less damaging :)
