### ISSUE TITLE
double escaping weirdness required by Nautilus

### ISSUE THREAD

**Issue by balmas** [Capitains/Nautilus#5]
See https://github.com/PerseusDL/canonical-greekLit/pull/110

without this Nautilus produces inventory with invalid entities because it seems to be writing out `&amp;` as an unescaped `&`

**Comment by PonteIneptique** [comment]
Is this fixed ? @balmas

**Comment by balmas** [comment]
Nope needs further investigation.

**Comment by PonteIneptique** [comment]
Let's say it's closed otherwise we would have heard about it.
