### ISSUE TITLE
Fix how Nautilus Resolver deals with missing files

### ISSUE THREAD

**Issue by sonofmun** [Capitains/Nautilus#55]
https://github.com/Capitains/Nautilus/blob/master/capitains_nautilus/cts/resolver.py#L284-L289
"Dealing with this could be done by raising an unknown collection is the file is unknown :)"
See https://github.com/Capitains/MyCapytain/issues/129 for reference.

**Comment by sonofmun** [comment]
Question @PonteIneptique : Do you mean with "raising an unknown collection" that I should check if the file exists and, if it doesn't, it should warn or error with a `MyCapytain.errors.UnknownCollection` error?

**Comment by PonteIneptique** [comment]
```python
if not isfile(file):
   raise UnknownCollection("File matching %s does not exist" % file)

**Comment by PonteIneptique** [comment]
Or something like that :)

**Comment by sonofmun** [comment]
Gotcha. That seems more extreme that what I did in MyCapytain, where it only logged a warning instead of raising an error.

**Comment by PonteIneptique** [comment]
In Flask, we need error to be raised, in order to throw a 404 or equivalent error :)

**Comment by sonofmun** [comment]
Gotcha. That's what I figured.

**Comment by sonofmun** [comment]
I don't have permission to push to Nautilus. Should I fork? Or do you want to give me permission?

**Comment by sonofmun** [comment]
I assume this one can be closed.
