### ISSUE TITLE
Implement file system caching

### ISSUE THREAD

**Issue by sonofmun** [Capitains/Nautilus#58]
@PonteIneptique 
If I am reading the code correctly, it looks like the option to use `werkzeug.FileSystemCache` is already implemented here: https://github.com/Capitains/Nautilus/blob/master/capitains_nautilus/cmd.py#L34-L36
Would it be enough just to change the configuration on the server (in the Puppet file?) to set `--cache filesystem`?

**Comment by PonteIneptique** [comment]
Yes it's definitely implemented. What you need to change is not this but https://github.com/OpenGreekAndLatin/leipzig_cts/blob/master/modules/capitains/templates/app.py.erb
