### ISSUE TITLE
language handling for editions in inventory?

### ISSUE THREAD

**Issue by balmas** [Capitains/Nautilus#6]
Not sure where this problem is coming in yet but Nemo using Nautilus doesn't display language for editions, but using the eXist CTS 5 repo it does, so I'm guessing the language for editions isn't being carried forward properly in the inventory. Haven't had a chance to track it further yet.

**Comment by PonteIneptique** [comment]
Ok, I think I have an idea where the issue come from : basically, the way I build the resource, I might be losing the lang information for edition only, because it was fed automatically through real (and not chunk) inventory parsing.

**Comment by PonteIneptique** [comment]
Fixed by @c5e80f9
