### ISSUE TITLE
GetValidReff fails for urn:cts:latinLit:phi0474.phi057.perseus-lat1:3.1

### ISSUE THREAD

**Issue by konstantinschulz** [Capitains/Nautilus#84]
A HTTP GET request to https://cts.perseids.org/api/cts/?request=GetValidReff&urn=urn:cts:latinLit:phi0474.phi057.perseus-lat1:3.1 throws back a 500 error. 
Subreferences of other books/chapters in the same work seem to be alright, e.g. the validReff for 2.1 or 4.1 .
Might be an upstream issue with the Perseus text data, though. So feel free to delete this issue if it is not appropriate here.

**Comment by PonteIneptique** [comment]
THis is indeed an issue with an implementation here.
